/* Educational topics. Short, sourced, interactive in the UI. */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else { root.NA = root.NA || {}; root.NA.learn = api; }
})(typeof self !== "undefined" ? self : this, function () {
  const TOPICS = [
    { id: "blast", q: "What is blast?", sourceIds: ["glasstone-1977", "lovelace-1962"], body: "A nuclear burst heats air so fast that a shock wave moves outward. Overpressure is how much the shock raises air pressure above normal. This app scales published 1 Mt contour radii by the cube root of yield. 20 psi is drawn as extreme structural damage, 5 psi as major, 1 psi as lighter damage including broken windows. The 2 psi line is interpolated." },
    { id: "thermal", q: "What is thermal radiation?", sourceIds: ["glasstone-1977", "sublette-faq"], body: "The fireball emits a pulse of heat and light. Fluence is energy per area, shown here in cal/cm². The colour field falls off continuously. It is a clear-day estimate, not a map of fires. Clothing, cloud and hills change the real exposure." },
    { id: "prompt", q: "What is prompt radiation?", sourceIds: ["glasstone-1977", "sandia-2022", "iaea-radiation"], body: "Prompt radiation is neutrons and gamma rays emitted in about the first minute. It is not dust and it is not fallout. Air absorbs it, so the radius grows only slowly with yield. Glasstone's charts carry roughly a factor-of-two uncertainty." },
    { id: "fallout", q: "What is fallout?", sourceIds: ["glasstone-1977", "miller-1964", "ready-gov"], body: "If the fireball touches the ground, soil and debris can be made radioactive and carried by the wind. That is fallout. An air burst in this app does not draw a local fallout plume. Fallout arrival is hours, not seconds, and depends on weather this model does not forecast." },
    { id: "wind", q: "Why does wind matter?", sourceIds: ["miller-1964", "mit-fallout", "sandia-2022"], body: "Wind direction sets where a plume goes. Wind speed changes arrival time and how stretched the pattern is. The MIT educational calculator and Miller's scaling studies both treat wind as an input. Changing the 15 or 30 mph assumption here changes the drawing. It does not make the drawing a forecast." },
    { id: "height", q: "Why does burst height matter?", sourceIds: ["glasstone-1977"], body: "A contact surface burst couples more energy into the ground and lofted debris, and its air-blast radii are smaller than an air burst of the same yield in the reference curves used here (about 4.4 km versus 7.0 km to 5 psi at 1 Mt). Height is a scenario assumption, not a targeting control." },
    { id: "circles", q: "Why are damage boundaries not perfect circles?", sourceIds: ["glasstone-1977", "fema-planning"], body: "Published curves assume flat ground and uniform air. Hills, city canyons and weather bend a real shock. Fallout is stretched by wind, so it is drawn as a plume. Even the circular blast lines are model contours, not guarantees that every building on the line fails the same way." },
    { id: "casualties", q: "Why are casualty estimates uncertain?", sourceIds: ["sandia-2022", "fema-planning", "iaea-radiation"], body: "Harm depends on shielding, time of day, medical care and who is indoors. This app does not invent a death count. For the Trinity test it also does not assign one: that shot was in the desert. Historical city figures, when quoted elsewhere, are estimates with sources — they are not computed here." },
    { id: "infra", q: "What happens to infrastructure?", sourceIds: ["fema-planning", "glasstone-1977"], body: "Blast damages buildings, bridges and utilities where overpressure is high. Window breakage can extend much farther. This build has no road, hospital or power-grid map, so sector rows are categories inferred from the physical contours, not an asset inventory. Electromagnetic pulse is not modelled." },
    { id: "econ", q: "What happens economically?", sourceIds: ["natural-earth", "fema-planning"], body: "The money range is an exposure share of Natural Earth GDP_MD_EST (mostly 2016 US dollars) times an assumed damage fraction. Confidence is low. Missing GDP rows are skipped rather than filled in." },
    { id: "response", q: "How does emergency response work?", sourceIds: ["ready-gov", "fema-planning"], body: "Public guidance for a nuclear explosion emphasises getting inside a sturdy building, staying inside, and waiting for official information, because fallout dose falls with time and shielding. Responders also have to deal with damaged hospitals and roads. This simulator is not a live warning system." }
  ];
  return { TOPICS: TOPICS };
});
